---
- hosts: dell_hosts
  sudo: yes
  gather_facts: False
  environment:
    http_proxy: http://<proxy_FQDN>:8080
    https_proxy: http://<proxy_FQDN>:8080
  tasks:
    - name: Deploy Docker vdbench container
      shell: docker run --device=/dev/sdc:/dev/xvdc --device=/dev/sda:/dev/sdax --device=/dev/sdb:/dev/sdbx --device=/dev/sdd:/dev/sddx --device=/dev/sde:/dev/sdex --device=/dev/sdf:/dev/sdfx --device=/dev/sdg:/dev/sdgx --device=/dev/sdh:/dev/sdhx --device=/dev/sdi:/dev/sdix --device=/dev/sdj:/dev/sdjx -i --name vdbench-10drive wmckeigney/vdbench-10drive
